spring:
    datasource:
        url: jdbc:mysql://localhost:3306/astar_hub
        username: root 
        password: Hung12062005@
    jpa:
        hibernate: 
            ddl-auto: update # không tự sửa cấu trúc bảng 
        show-sql: true 
    # mvc:
    #     throw-exception-if-no-handler-found: true -> cần thiết với phiên bản cũ, Ném lỗi NoHandlerFoundException khi không có controller xử lý url.
    #     Nếu chỉ dùng mỗi nó, thì nó sẽ không báo lỗi ngay, mà ResourceHandler nhận tìm xem có file tĩnh nào không -> ko báo lỗi nữa.

    web: # phiên bản spring 4 chỉ cần cái này là đủ. Đó là lí do vì sao dòng trên comment vẫn bắt lỗi ngon.
        resources:
            add-mappings: false # cấm tìm các file tĩnh trong static như html,... phiên bản 4 này 
            # => nó ko tìm được file tĩnh tương ứng -> nó sẽ ném lỗi luôn
            # Nếu chỉ dùng mỗi cái này ở phiên bản spring cũ, khi không tìm được, nó sẽ chuyển đến trang /error nên hàm trong GlobalException không hứng đc lỗi.
server:
    port: 8080

logging:
    level:
        root: DEBUG
    file:
        name: logs/check-log.log  
    logback:
        rollingpolicy:
            # Rolling theo phút 
            file-name-pattern: logs/archived/check-log-%d{yyyy-MM-dd_HH-mm}.%i.log 
            # Chỉ giữ lại 1 file archived 
            max-history: 1
            max-file-size: 1MB
            # quá 10MB thì i sẽ tăng lên 