spring:
    application:
        name: project
    profiles:
        active: dev

admin:
    bootstrap:
        fullname: ${ADMIN_FULLNAME:Admin}
        username: ${ADMIN_USERNAME:admin}
        password: ${ADMIN_PASSWORD:admin}
        email: ${ADMIN_EMAIL:admin@alandas.site}

 
# ```
# Ưu tiên từ CAO → THẤP:
# ──────────────────────
# 1. Command line arguments (--server.port=9090)
# 2. Environment variables (SERVER_PORT=9090)
# 3. application-{profile}.properties
# 4. application.properties
# 5. Default values trong code
# ```